version: '3'

services:
  builder:
    build:
      context: .
      args:
        - HOME=/user_home
    volumes:
      - .:/work
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker
    working_dir: /work
    environment:
      - XDG_CACHE_HOME=/user_home/.cache
      - XDG_CONFIG_HOME=/user_home/.config
      - XDG_DATA_HOME=/user_home/.local/share
